FROM golang:latest

RUN apt-get update \
    && apt-get install -y dnsutils git iptables ssh ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd --shell=/bin/bash --create-home ssh-it-user

RUN git clone https://github.com/tailscale/tailscale.git

WORKDIR /go/tailscale

RUN git checkout main \
    && sh build_dist.sh tailscale.com/cmd/tailscale \
    && sh build_dist.sh tailscale.com/cmd/tailscaled \
    && cp tailscale /usr/local/bin/ \
    && cp tailscaled /usr/local/bin/
