name: 🐞 Bug
description: File a bug/issue
title: "[Bug] <title>"
labels: ["bug", "needs triage"]
body:
  - type: checkboxes
    attributes:
      label: Is this a support request?
      description: This issue tracker is for bugs and feature requests only. If you need help, please use ask in our Discord community
      options:
        - label: This is not a support request
          required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Headscale version**: 0.22.3
          - **Tailscale version**: 1.64.0
      value: |
        - OS:
        - Headscale version:
        - Tailscale version:
      render: markdown
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Runtime environment
      options:
        - label: Headscale is behind a (reverse) proxy
          required: false
        - label: Headscale runs in a container
          required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        - Client netmap dump (see below)
        - ACL configuration
        - Headscale configuration

        Dump the netmap of tailscale clients:
        `tailscale debug netmap > DESCRIPTIVE_NAME.json`

        Please provide information describing the netmap, which client, which headscale version etc.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
