package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"text/template"
)

type Field struct {
	Name string
	Type string
	Tag  string
}

type ChangeStruct struct {
	Name   string
	IDType string
	Fields []Field
}

type TemplateData struct {
	Package string
	Structs []ChangeStruct
}

const generatedCodeTemplate = `// Code generated by changegen. DO NOT EDIT.
package {{.Package}}

{{range .Structs}}{{if ne .Name "Change"}}
// {{.Name}} merge method
func (c {{.Name}}) merge(other {{.Name}}) {{.Name}} {
	{{if .IDType}}// Use non-zero ID
	id := c.ID
	if id == 0 {
		id = other.ID
	}
	{{end}}
	
	return {{.Name}}{
		{{if .IDType}}ID: id,
		{{end}}{{range .Fields}}{{if ne .Tag "id"}}{{.Name}}: c.{{.Name}} || other.{{.Name}},
		{{end}}{{end}}
	}
}

// {{.Name}} hasChange method
func (c {{.Name}}) hasChange() bool {
	return {{if .IDType}}c.ID != 0{{range .Fields}}{{if ne .Tag "id"}} || c.{{.Name}}{{end}}{{end}}{{else}}{{range $i, $field := .Fields}}{{if $i}} || {{end}}c.{{.Name}}{{end}}{{end}}
}{{end}}

{{if .IDType}}
// {{.Name}} constructor functions
{{$structName := .Name}}{{$idType := .IDType}}{{range .Fields}}{{if ne .Tag "id"}}func {{cleanName .Name $structName}}(id {{$idType}}) Change {
	return Change{
		{{trimSuffix $structName "Change"}}: {{$structName}}{
			ID: id,
			{{.Name}}: true,
		},
	}
}

{{end}}{{end}}

// {{.Name}} set methods (builder pattern)
{{range .Fields}}{{if ne .Tag "id"}}func (c Change) Set{{.Name}}(id {{$idType}}) Change {
	c.{{trimSuffix $structName "Change"}}.ID = id
	c.{{trimSuffix $structName "Change"}}.{{.Name}} = true
	return c
}

{{end}}{{end}}{{end}}

{{if eq .Name "Change"}}
// Change merge method
func (c Change) Merge(other Change) Change {
	return Change{
		{{range .Fields}}{{if eq .Tag "simple"}}{{.Name}}: c.{{.Name}} || other.{{.Name}},
		{{else if eq .Tag "struct"}}{{trimSuffix .Name "Change"}}: c.{{trimSuffix .Name "Change"}}.merge(other.{{trimSuffix .Name "Change"}}),
		{{end}}{{end}}
	}
}

// HasChange checks if any field indicates a change occurred
func (c Change) HasChange() bool {
	return {{range $i, $field := .Fields}}{{if eq .Tag "simple"}}{{if $i}} ||
		{{end}}c.{{.Name}}{{else if eq .Tag "struct"}} ||
		c.{{trimSuffix .Name "Change"}}.hasChange(){{end}}{{end}}
}

// System-level constructor functions
{{range .Fields}}{{if eq .Tag "simple"}}func {{cleanSystemName .Name}}() Change {
	return Change{
		{{.Name}}: true,
	}
}

{{end}}{{end}}

// System-level set methods
{{range .Fields}}{{if eq .Tag "simple"}}func (c Change) Set{{.Name}}() Change {
	c.{{.Name}} = true
	return c
}

{{end}}{{end}}{{end}}

{{end}}`

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: changegen <source.go>")
		os.Exit(1)
	}

	filename := os.Args[1]
	
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	data := TemplateData{
		Package: node.Name.Name,
		Structs: []ChangeStruct{},
	}

	ast.Inspect(node, func(n ast.Node) bool {
		if typeSpec, ok := n.(*ast.TypeSpec); ok {
			if structType, ok := typeSpec.Type.(*ast.StructType); ok {
				structName := typeSpec.Name.Name
				
				if strings.Contains(structName, "Change") || structName == "Change" {
					changeStruct := parseChangeStruct(structName, structType)
					data.Structs = append(data.Structs, changeStruct)
				}
			}
		}
		return true
	})

	tmpl := template.Must(template.New("change").Funcs(template.FuncMap{
		"cleanName":       cleanName,
		"cleanSystemName": cleanSystemName,
		"trimSuffix":      strings.TrimSuffix,
	}).Parse(generatedCodeTemplate))
	
	outputFile := strings.Replace(filename, ".go", "_generated.go", 1)
	f, err := os.Create(outputFile)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = tmpl.Execute(f, data)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Generated %s\n", outputFile)
}

func parseChangeStruct(name string, structType *ast.StructType) ChangeStruct {
	changeStruct := ChangeStruct{
		Name:   name,
		Fields: []Field{},
	}

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		
		fieldName := field.Names[0].Name
		fieldType := getTypeString(field.Type)
		
		tag := "simple"
		if fieldName == "ID" {
			tag = "id"
			changeStruct.IDType = fieldType
		} else if fieldType == "NodeChange" || fieldType == "UserChange" {
			tag = "struct"
		}
		
		changeStruct.Fields = append(changeStruct.Fields, Field{
			Name: fieldName,
			Type: fieldType,
			Tag:  tag,
		})
	}

	return changeStruct
}

func getTypeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getTypeString(t.X)
	case *ast.SelectorExpr:
		return getTypeString(t.X) + "." + t.Sel.Name
	default:
		return "unknown"
	}
}

func cleanName(fieldName, structName string) string {
	prefix := ""
	if strings.HasPrefix(structName, "Node") {
		prefix = "Node"
	} else if strings.HasPrefix(structName, "User") {
		prefix = "User"
	}
	
	switch {
	case strings.Contains(fieldName, "Online"):
		return prefix + "Online"
	case strings.Contains(fieldName, "Offline"):
		return prefix + "Offline"
	case strings.Contains(fieldName, "New") || strings.Contains(fieldName, "Added"):
		return prefix + "Added"
	case strings.Contains(fieldName, "Removed"):
		return prefix + "Removed"
	case strings.Contains(fieldName, "Key"):
		return prefix + "KeyChanged"
	case strings.Contains(fieldName, "Tags"):
		return prefix + "TagsChanged"
	case strings.Contains(fieldName, "Routes"):
		return prefix + "RoutesChanged"
	case strings.Contains(fieldName, "Expiry"):
		return prefix + "ExpiryChanged"
	case strings.Contains(fieldName, "Hostinfo"):
		return prefix + "HostinfoChanged"
	case strings.Contains(fieldName, "Full"):
		return prefix + "FullUpdate"
	default:
		cleanField := strings.TrimSuffix(fieldName, "Changed")
		return prefix + cleanField
	}
}

func cleanSystemName(fieldName string) string {
	switch {
	case fieldName == "Full":
		return "FullUpdate"
	case strings.HasSuffix(fieldName, "Changed"):
		base := strings.TrimSuffix(fieldName, "Changed")
		return base + "Update"
	default:
		return fieldName + "Update"
	}
}