FROM docker.io/golang:1.26.5-trixie AS builder
ARG VERSION=dev
ENV GOPATH /go
WORKDIR /go/src/headscale

COPY go.mod go.sum /go/src/headscale/
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/headscale ./cmd/headscale

FROM debian:trixie-slim

RUN apt-get --update install --no-install-recommends --yes \
    bash ca-certificates curl dnsutils findutils iproute2 jq less procps python3 sqlite3 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/headscale /etc/headscale /var/lib/headscale

COPY --from=builder /go/bin/headscale /usr/local/bin/headscale

COPY e2e/config.yaml /etc/headscale/config.yaml
COPY e2e/bootstrap.sh /usr/local/bin/bootstrap.sh
RUN chmod +x /usr/local/bin/bootstrap.sh

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/bootstrap.sh"]
