// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package types

import (
	"database/sql"
	"net/netip"
	"time"

	"gorm.io/gorm"
	"tailscale.com/tailcfg"
	"tailscale.com/types/key"
)

// Clone makes a deep copy of User.
// The result aliases no memory with the original.
func (src *User) Clone() *User {
	if src == nil {
		return nil
	}
	dst := new(User)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _UserCloneNeedsRegeneration = User(struct {
	gorm.Model
	Name               string
	DisplayName        string
	Email              string
	ProviderIdentifier sql.NullString
	Provider           string
	ProfilePicURL      string
}{})

// Clone makes a deep copy of Node.
// The result aliases no memory with the original.
func (src *Node) Clone() *Node {
	if src == nil {
		return nil
	}
	dst := new(Node)
	*dst = *src
	dst.Endpoints = append(src.Endpoints[:0:0], src.Endpoints...)
	dst.Hostinfo = src.Hostinfo.Clone()
	if dst.IPv4 != nil {
		dst.IPv4 = new(*src.IPv4)
	}
	if dst.IPv6 != nil {
		dst.IPv6 = new(*src.IPv6)
	}
	if dst.UserID != nil {
		dst.UserID = new(*src.UserID)
	}
	if dst.User != nil {
		dst.User = new(*src.User)
	}
	dst.Tags = append(src.Tags[:0:0], src.Tags...)
	if dst.AuthKeyID != nil {
		dst.AuthKeyID = new(*src.AuthKeyID)
	}
	dst.AuthKey = src.AuthKey.Clone()
	if dst.Expiry != nil {
		dst.Expiry = new(*src.Expiry)
	}
	if dst.LastSeen != nil {
		dst.LastSeen = new(*src.LastSeen)
	}
	dst.ApprovedRoutes = append(src.ApprovedRoutes[:0:0], src.ApprovedRoutes...)
	if dst.DeletedAt != nil {
		dst.DeletedAt = new(*src.DeletedAt)
	}
	if dst.IsOnline != nil {
		dst.IsOnline = new(*src.IsOnline)
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeCloneNeedsRegeneration = Node(struct {
	ID             NodeID
	MachineKey     key.MachinePublic
	NodeKey        key.NodePublic
	DiscoKey       key.DiscoPublic
	Endpoints      []netip.AddrPort
	Hostinfo       *tailcfg.Hostinfo
	IPv4           *netip.Addr
	IPv6           *netip.Addr
	Hostname       string
	GivenName      string
	UserID         *uint
	User           *User
	RegisterMethod string
	Tags           []string
	AuthKeyID      *uint64
	AuthKey        *PreAuthKey
	Expiry         *time.Time
	LastSeen       *time.Time
	ApprovedRoutes []netip.Prefix
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	IsOnline       *bool
	Unhealthy      bool
	SessionEpoch   uint64
}{})

// Clone makes a deep copy of PreAuthKey.
// The result aliases no memory with the original.
func (src *PreAuthKey) Clone() *PreAuthKey {
	if src == nil {
		return nil
	}
	dst := new(PreAuthKey)
	*dst = *src
	dst.Hash = append(src.Hash[:0:0], src.Hash...)
	if dst.UserID != nil {
		dst.UserID = new(*src.UserID)
	}
	if dst.User != nil {
		dst.User = new(*src.User)
	}
	dst.Tags = append(src.Tags[:0:0], src.Tags...)
	if dst.CreatedAt != nil {
		dst.CreatedAt = new(*src.CreatedAt)
	}
	if dst.Expiration != nil {
		dst.Expiration = new(*src.Expiration)
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PreAuthKeyCloneNeedsRegeneration = PreAuthKey(struct {
	ID         uint64
	Key        string
	Prefix     string
	Hash       []byte
	UserID     *uint
	User       *User
	Reusable   bool
	Ephemeral  bool
	Used       bool
	Tags       []string
	CreatedAt  *time.Time
	Expiration *time.Time
}{})
