// Code generated by changegen. DO NOT EDIT.
package change






// Change merge method
func (c Change) Merge(other Change) Change {
	return Change{
		Full: c.Full || other.Full,
		Node: c.Node.merge(other.Node),
		User: c.User.merge(other.User),
		DERPChanged: c.DERPChanged || other.DERPChanged,
		PolicyChanged: c.PolicyChanged || other.PolicyChanged,
		ExtraRecordsChanged: c.ExtraRecordsChanged || other.ExtraRecordsChanged,
		
	}
}

// HasChange checks if any field indicates a change occurred
func (c Change) HasChange() bool {
	return c.Full ||
		c.Node.hasChange() ||
		c.User.hasChange() ||
		c.DERPChanged ||
		c.PolicyChanged ||
		c.ExtraRecordsChanged
}

// System-level constructor functions
func FullUpdate() Change {
	return Change{
		Full: true,
	}
}

func DERPUpdate() Change {
	return Change{
		DERPChanged: true,
	}
}

func PolicyUpdate() Change {
	return Change{
		PolicyChanged: true,
	}
}

func ExtraRecordsUpdate() Change {
	return Change{
		ExtraRecordsChanged: true,
	}
}



// System-level set methods
func (c Change) SetFull() Change {
	c.Full = true
	return c
}

func (c Change) SetDERPChanged() Change {
	c.DERPChanged = true
	return c
}

func (c Change) SetPolicyChanged() Change {
	c.PolicyChanged = true
	return c
}

func (c Change) SetExtraRecordsChanged() Change {
	c.ExtraRecordsChanged = true
	return c
}




// NodeChange merge method
func (c NodeChange) merge(other NodeChange) NodeChange {
	// Use non-zero ID
	id := c.ID
	if id == 0 {
		id = other.ID
	}
	
	
	return NodeChange{
		ID: id,
		FullChange: c.FullChange || other.FullChange,
		ExpiryChanged: c.ExpiryChanged || other.ExpiryChanged,
		RoutesChanged: c.RoutesChanged || other.RoutesChanged,
		Online: c.Online || other.Online,
		Offline: c.Offline || other.Offline,
		HostinfoChanged: c.HostinfoChanged || other.HostinfoChanged,
		NewNode: c.NewNode || other.NewNode,
		RemovedNode: c.RemovedNode || other.RemovedNode,
		KeyChanged: c.KeyChanged || other.KeyChanged,
		TagsChanged: c.TagsChanged || other.TagsChanged,
		
	}
}

// NodeChange hasChange method
func (c NodeChange) hasChange() bool {
	return c.ID != 0 || c.FullChange || c.ExpiryChanged || c.RoutesChanged || c.Online || c.Offline || c.HostinfoChanged || c.NewNode || c.RemovedNode || c.KeyChanged || c.TagsChanged
}


// NodeChange constructor functions
func NodeFullUpdate(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			FullChange: true,
		},
	}
}

func NodeExpiryChanged(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			ExpiryChanged: true,
		},
	}
}

func NodeRoutesChanged(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			RoutesChanged: true,
		},
	}
}

func NodeOnline(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			Online: true,
		},
	}
}

func NodeOffline(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			Offline: true,
		},
	}
}

func NodeHostinfoChanged(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			HostinfoChanged: true,
		},
	}
}

func NodeAdded(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			NewNode: true,
		},
	}
}

func NodeRemoved(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			RemovedNode: true,
		},
	}
}

func NodeKeyChanged(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			KeyChanged: true,
		},
	}
}

func NodeTagsChanged(id NodeID) Change {
	return Change{
		Node: NodeChange{
			ID: id,
			TagsChanged: true,
		},
	}
}



// NodeChange set methods (builder pattern)
func (c Change) SetFullChange(id NodeID) Change {
	c.Node.ID = id
	c.Node.FullChange = true
	return c
}

func (c Change) SetExpiryChanged(id NodeID) Change {
	c.Node.ID = id
	c.Node.ExpiryChanged = true
	return c
}

func (c Change) SetRoutesChanged(id NodeID) Change {
	c.Node.ID = id
	c.Node.RoutesChanged = true
	return c
}

func (c Change) SetOnline(id NodeID) Change {
	c.Node.ID = id
	c.Node.Online = true
	return c
}

func (c Change) SetOffline(id NodeID) Change {
	c.Node.ID = id
	c.Node.Offline = true
	return c
}

func (c Change) SetHostinfoChanged(id NodeID) Change {
	c.Node.ID = id
	c.Node.HostinfoChanged = true
	return c
}

func (c Change) SetNewNode(id NodeID) Change {
	c.Node.ID = id
	c.Node.NewNode = true
	return c
}

func (c Change) SetRemovedNode(id NodeID) Change {
	c.Node.ID = id
	c.Node.RemovedNode = true
	return c
}

func (c Change) SetKeyChanged(id NodeID) Change {
	c.Node.ID = id
	c.Node.KeyChanged = true
	return c
}

func (c Change) SetTagsChanged(id NodeID) Change {
	c.Node.ID = id
	c.Node.TagsChanged = true
	return c
}






// UserChange merge method
func (c UserChange) merge(other UserChange) UserChange {
	// Use non-zero ID
	id := c.ID
	if id == 0 {
		id = other.ID
	}
	
	
	return UserChange{
		ID: id,
		NewUser: c.NewUser || other.NewUser,
		RemovedUser: c.RemovedUser || other.RemovedUser,
		
	}
}

// UserChange hasChange method
func (c UserChange) hasChange() bool {
	return c.ID != 0 || c.NewUser || c.RemovedUser
}


// UserChange constructor functions
func UserAdded(id UserID) Change {
	return Change{
		User: UserChange{
			ID: id,
			NewUser: true,
		},
	}
}

func UserRemoved(id UserID) Change {
	return Change{
		User: UserChange{
			ID: id,
			RemovedUser: true,
		},
	}
}



// UserChange set methods (builder pattern)
func (c Change) SetNewUser(id UserID) Change {
	c.User.ID = id
	c.User.NewUser = true
	return c
}

func (c Change) SetRemovedUser(id UserID) Change {
	c.User.ID = id
	c.User.RemovedUser = true
	return c
}





