// Code generated by "stringer -type=Change"; DO NOT EDIT.

package change

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangeUnknown-0]
	_ = x[Full-9]
	_ = x[Policy-11]
	_ = x[DERP-12]
	_ = x[ExtraRecords-13]
	_ = x[NodeCameOnline-21]
	_ = x[NodeWentOffline-22]
	_ = x[NodeRemove-23]
	_ = x[NodeKeyExpiry-24]
	_ = x[NodeNewOrUpdate-25]
	_ = x[UserNewOrUpdate-51]
	_ = x[UserRemove-52]
}

const (
	_Change_name_0 = "ChangeUnknown"
	_Change_name_1 = "Full"
	_Change_name_2 = "PolicyDERPExtraRecords"
	_Change_name_3 = "NodeCameOnlineNodeWentOfflineNodeRemoveNodeKeyExpiryNodeNewOrUpdate"
	_Change_name_4 = "UserNewOrUpdateUserRemove"
)

var (
	_Change_index_2 = [...]uint8{0, 6, 10, 22}
	_Change_index_3 = [...]uint8{0, 14, 29, 39, 52, 67}
	_Change_index_4 = [...]uint8{0, 15, 25}
)

func (i Change) String() string {
	switch {
	case i == 0:
		return _Change_name_0
	case i == 9:
		return _Change_name_1
	case 11 <= i && i <= 13:
		i -= 11
		return _Change_name_2[_Change_index_2[i]:_Change_index_2[i+1]]
	case 21 <= i && i <= 25:
		i -= 21
		return _Change_name_3[_Change_index_3[i]:_Change_index_3[i+1]]
	case 51 <= i && i <= 52:
		i -= 51
		return _Change_name_4[_Change_index_4[i]:_Change_index_4[i+1]]
	default:
		return "Change(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
