apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # TODO: figure out how to get kustomize to interpolate this, or use a transformer
    #email: $(CONTACT_EMAIL)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-staging-acc-key
    solvers:
      - http01:
          ingress:
            class: traefik
