package main

//go:generate go run ./gh-action-integration-generator.go

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"slices"
	"strings"
)

// excludedFromNixChecks lists tests the hermetic nix-VM checks cannot run, with
// the reason. They still run via cmd/hi, where the missing resource exists.
var excludedFromNixChecks = map[string]string{
	// Verifies connectivity through Tailscale's *public* DERP relays
	// (HEADSCALE_DERP_URLS=controlplane.tailscale.com). A hermetic offline VM
	// has no internet and the nix sandbox forbids network.
	"TestPingAllByIPPublicDERP": "requires public internet DERP",

	// Also routes DERP through Tailscale's public relays: tailscale-rs cannot
	// validate the embedded DERP's self-signed cert (WithPublicDERP in the
	// test), so it needs the same internet access PublicDERP does.
	"TestTailscaleRustAxum": "requires public internet DERP (tailscale-rs)",

	// These drive `docker network disconnect`/`connect` to simulate cable pulls.
	// In the VM's nested docker, libnetwork intermittently fails the reconnect
	// ("failed to set gateway: network is unreachable" — a stale IPAM/endpoint
	// reservation), which does not happen against a host docker daemon. They run
	// reliably via cmd/hi in the legacy pipeline.
	"TestHASubnetRouterFailoverDockerDisconnect":     "docker reconnect unreliable in nested VM docker",
	"TestHASubnetRouterFailoverBothOfflineCablePull": "docker reconnect unreliable in nested VM docker",

	// Ping-driven HA failover: after a router recovers it asserts router 2 stays
	// primary and traffic still traceroutes through it. In the VM's nested docker
	// that data-plane state never converges (a 4x ScaledTimeout budget did not
	// help — behaviour, not timing); it holds against a host docker daemon.
	"TestHASubnetRouterPingFailover": "ping-failover data plane doesn't converge in nested VM docker",
}

// testsToSplit defines tests whose subtests are run as separate checks. Key is
// the test function, value is a list of subtest prefixes; each prefix becomes
// its own check as "TestName/prefix.*". TestAutoApproveMultiNetwork fans out
// over approver × policy-mode × advertise (24 subtests); running all of them in
// one nested-docker VM check overruns the timeout, so split by approver into
// 6 checks of 4 — fewer sequential docker scenarios per check.
var testsToSplit = map[string][]string{
	"TestAutoApproveMultiNetwork": {
		"authkey-tag",
		"authkey-user",
		"authkey-group",
		"webauth-tag",
		"webauth-user",
		"webauth-group",
	},
}

// expandTests replaces any splittable test with one entry per subtest prefix.
// The ".*" lets the check's "^...$"-wrapped -test.run match the full subtest
// names (e.g. authkey-tag-advertiseduringup-false-pol-database).
func expandTests(tests []string) []string {
	expanded := make([]string, 0, len(tests))
	for _, test := range tests {
		prefixes, ok := testsToSplit[test]
		if !ok {
			expanded = append(expanded, test)
			continue
		}

		for _, prefix := range prefixes {
			expanded = append(expanded, fmt.Sprintf("%s/%s.*", test, prefix))
		}
	}

	return expanded
}

// This generator enumerates the integration test functions and writes them as
// nix lists (integration/tests.nix and integration/postgres-tests.nix). The
// flake maps each entry to a NixOS-VM check (sqlite for all, plus a postgres
// variant for the subset) — see nix/tests/integration.nix. One check per test
// function; the GitHub workflow derives its matrix from these checks.

func findTests() []string {
	rgBin, err := exec.LookPath("rg")
	if err != nil {
		log.Fatalf("failed to find rg (ripgrep) binary")
	}

	args := []string{
		"--type", "go",
		"--regexp", "func (Test.+)\\(.*",
		"--max-depth", "1",
		"../../integration/",
		"--replace", "$1",
		"--sort", "path",
		"--no-line-number",
		"--no-filename",
		"--no-heading",
	}

	cmd := exec.Command(rgBin, args...)
	var out bytes.Buffer
	cmd.Stdout = &out
	err = cmd.Run()
	if err != nil {
		log.Fatalf("failed to run command: %s", err)
	}

	tests := strings.Split(strings.TrimSpace(out.String()), "\n")
	return tests
}

// writeNixList writes the test function names as a nix list, consumed by
// flake.nix to generate one integration check per test.
func writeNixList(tests []string, nixPath string) {
	var b strings.Builder
	b.WriteString("# Generated by gh-action-integration-generator.go; do not edit.\n")
	b.WriteString("[\n")
	for _, test := range tests {
		fmt.Fprintf(&b, "  %q\n", test)
	}
	b.WriteString("]\n")

	if err := os.WriteFile(nixPath, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("failed to write %s: %s", nixPath, err)
	}

	fmt.Printf("Nix list (%s) updated successfully\n", nixPath)
}

func main() {
	tests := findTests()

	tests = slices.DeleteFunc(tests, func(name string) bool {
		if reason, ok := excludedFromNixChecks[name]; ok {
			log.Printf("excluding %s from nix checks: %s", name, reason)
			return true
		}
		return false
	})

	// Split heavy tests into per-subtest checks (after exclusion, so an excluded
	// test is never expanded).
	tests = expandTests(tests)

	// Selected tests also run against PostgreSQL to verify database
	// compatibility (a postgres-variant check per name).
	postgresTestNames := []string{
		"TestACLAllowUserDst",
		"TestPingAllByIP",
		"TestEphemeral2006DeletedTooQuickly",
		"TestPingAllByIPManyUpDown",
		"TestSubnetRouterMultiNetwork",
	}

	// Tests excluded from the hermetic nix checks still need to run somewhere,
	// so emit them for the legacy cmd/hi GitHub-Actions matrix (real internet).
	excluded := make([]string, 0, len(excludedFromNixChecks))
	for name := range excludedFromNixChecks {
		excluded = append(excluded, name)
	}
	slices.Sort(excluded)

	writeNixList(tests, "../../integration/tests.nix")
	writeNixList(postgresTestNames, "../../integration/postgres-tests.nix")
	writeJSONList(excluded, "../../integration/excluded-tests.json")
}

// writeJSONList writes the names as a JSON array, consumed as a GitHub-Actions
// matrix by the legacy cmd/hi workflow.
func writeJSONList(names []string, path string) {
	data, err := json.MarshalIndent(names, "", "  ")
	if err != nil {
		log.Fatalf("marshalling %s: %s", path, err)
	}

	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		log.Fatalf("failed to write %s: %s", path, err)
	}

	fmt.Printf("JSON list (%s) updated successfully\n", path)
}
