name: Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: nix develop --fallback --command bash -e {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            files:
              - '*.nix'
              - 'go.*'
              - '**/*.go'
              - 'integration_test/'
              - 'config-example.yaml'

      - uses: NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc # main
        if: steps.changed-files.outputs.files == 'true'
      - uses: Mic92/hestia/action@ff07bb902a9968ac0c3d0e51d90a606662a375d8 # main
        if: steps.changed-files.outputs.files == 'true'

      - name: Run tests
        if: steps.changed-files.outputs.files == 'true'
        env:
          # As of 2025-01-06, these env vars was not automatically
          # set anymore which breaks the initdb for postgres on
          # some of the database migration tests.
          LC_ALL: "en_US.UTF-8"
          LC_CTYPE: "en_US.UTF-8"
        run: gotestsum
