name: Integration Test v2 - kradalby

on: [pull_request]

jobs:
  integration-test-v2-kradalby:
    runs-on: [self-hosted, linux, x64, nixos, docker]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            *.nix
            go.*
            **/*.go
            integration_test/
            config-example.yaml

      # We currently only run one job at the time, so make sure
      # we just wipe all containers and all networks.
      - name: Clean up Docker
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker kill $(docker ps -q)
          docker network prune -f

      - name: Run general integration tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: nix develop --command -- make test_integration_v2_general
