name: "Vouch - Sync CODEOWNERS"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: vouch-manage
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: mitchellh/vouch/action/sync-codeowners@d66fa29a64600490892131ad87597c30c91fcac4 # v1.5.0
        with:
          repo: ${{ github.repository }}
          pull-request: "true"
          merge-immediately: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
